apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  selector:
    app: my-flask-app
  ports:
    - protocol: TCP
      port: 80   # Cổng bên ngoài Service
      targetPort: 5000  # Cổng trong container
  type: NodePort
