apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
        - name: my-flask-app
          image: tungvu1/my-flask-app:latest  # Thay đổi tên repository Docker Hub nếu cần
          ports:
            - containerPort: 5000  # Cổng mà Flask ứng dụng của bạn lắng nghe
